namespace BarberBossI.Domain.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceReportGenerationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceReportGenerationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBossI.Domain.Reports.ResourceReportGenerationMessages", typeof(ResourceReportGenerationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
       public static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }

        public static string CASH
        {
            get
            {
                return ResourceManager.GetString("CASH", resourceCulture);
            }
        }

        public static string CREDIT_CARD
        {
            get
            {
                return ResourceManager.GetString("CREDIT_CARD", resourceCulture);
            }
        }

        
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }

        public static string DEBIT_CARD
        {
            get
            {
                return ResourceManager.GetString("DEBIT_CARD", resourceCulture);
            }
        }
     
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        public static string ELETRONIC_TRANSFER
        {
            get
            {
                return ResourceManager.GetString("ELETRONIC_TRANSFER", resourceCulture);
            }
        }

        public static string PIX
        {
            get
            {
                return ResourceManager.GetString("PIX", resourceCulture);
            }
        }

        public static string EXPENSES_FOR
        {
            get
            {
                return ResourceManager.GetString("EXPENSES_FOR", resourceCulture);
            }
        }

        public static object INVOICES_FOR
        {
            get
            {
                return ResourceManager.GetString("INVOICES_FOR", resourceCulture);
            }

        }

        public static string PAYMENT_TYPE {
            get {
                return ResourceManager.GetString("PAYMENT_TYPE", resourceCulture);
            }
        }        
        
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }       
                
        public static string TOTAL_WON_IN
        {
            get
            {
                return ResourceManager.GetString("TOTAL_WON_IN", resourceCulture);
            }
        }
        
        public static string TOTAL_SPENT_IN
        {
            get
            {
                return ResourceManager.GetString("TOTAL_SPENT_IN", resourceCulture);
            }
        }


    }
}
